import React from "react";
import axios from "axios";
import {
  Image,
  StyleSheet,
  View,
  TouchableWithoutFeedback,
  Text,
  Button,
  ScrollView,
  TouchableOpacity
} from "react-native";
import { FileSystem, MailComposer } from "expo";
import { Card } from "react-native-elements";
const Expo = require("expo");
import { MaterialIcons } from "@expo/vector-icons";

import { api } from "../../api/api";

export default class SendEmail extends React.Component {
  static navigationOptions = {
    headerTitleStyle: { color: "#85c4ea" },
    headerTitle: "SEND YOUR REQUEST",
    headerStyle: { backgroundColor: "#white" },
    headerTintColor: "#85c4ea"
  };
  constructor() {
    super();
    this.state = {
      lastRequest: null,
      newRequest: null,
      uploaded: false,
      companyEmail: [],
      userId: null
    };
  }

  componentDidMount = async () => {
    const id = this.props.navigation.getParam("id", "no_id");
    const data = this.props.navigation.getParam("data", "no_data");
    await axios
      .get(api + "/api/professional/showDetails?id=" + data.companyId)
      .then(response => {
        this.setState(state => {
          state.companyEmail.push(response.data[0].email);
          return state;
        });
      })
      .catch(error => {
        console.log(error);
      });

    await axios
      .get(api + "/api/user/request/showLast?id=" + id + "&title=" + data.title)
      .then(response => {
        this.setState(state => {
          state.lastRequest = response.data;
          state.newRequest = data;

          return state;
        });
      });
    await axios
      .get(api + "/api/user/showDetails?id=" + id)
      .then(response => {
        this.setState(state => {
          state.userData = response.data[0];
          return state;
        });
      })

      .catch(err => console.log(err));
  };

  sendAsEmailToMany = () => {
    let uriArray = [];
    for (let i in this.state.lastRequest.data.editedImages) {
      uriArray.push(this.state.lastRequest.data.editedImages[i].uri);
    }
    this.props.navigation.navigate("SelectCompanies", {
      uriArray: uriArray,
      userData: this.state.userData,
      requestData: this.state.lastRequest.data.requestData
    });
  };

  createNewReq = () => {
    this.props.navigation.navigate("RequestFormular");
  };

  sendAsEmail = async () => {
    let uriArray = [];

    for (let i in this.state.lastRequest.data.editedImages) {
      uriArray.push(this.state.lastRequest.data.editedImages[i].uri);
    }

    /**
     * informations to be implemented:
     *
     * recipients will be updated with the company email
     * subject or more emails, if you want to send to many diferent
     * companies
     *
     *
     */

    await MailComposer.composeAsync({
      recipients: ["sergiousle@gmail.com", ...this.state.companyEmail],
      subject: `estimation request from ${this.state.userData.first_name}`,
      body: `To Whom It May Concern,
      
      I would like to ask for a price estimation for an inner reform 
      in my house.
      More details in the following text:
            
      Title: ${this.state.lastRequest.data.requestData.title}
      Description: ${this.state.lastRequest.data.requestData.description}
      Budget: ${this.state.lastRequest.data.requestData.budget}
      Preferred starting date:${this.state.lastRequest.data.requestData.date}
      I attached to this email some pictures in order to illustrate better 
      my expectation.
      I look forward to have news from you,
      Thanks in advance, 
      ${this.state.userData.first_name}  ${this.state.userData.last_name}


      ________________________________________________
      this email was automatically generated by BUILDY.
      Please note that BUILDY does not take any responsibility
      for any requests`,
      attachments: uriArray
    });
  };

  keyExtractor = (item, index) => String(item._id);

  render() {
    const request = this.state.lastRequest;

    console.log(
      "Request",
      request,
      "this.state.lastRequest",
      this.state.lastRequest
    );
    if (request !== null) {
      return (
        <View style={styles.container}>
          <View style={styles.request_data}>
            <ScrollView
              style={{ flex: 1, marginTop: 90 }}
              contentContainerStyle={{ width: "100%", alignItems: "center" }}
            >
              <Card style={styles.infos}>
                <Text style={styles.title}>Your estimation request</Text>
                <Text style={[styles.title, styles.tagline]}>
                  review your information before you send it!
                </Text>

                <View style={[styles.infos, styles.paragraphText]}>
                  <Text>Title: {request.data.requestData.title}</Text>
                  <Text>
                    Description:{" "}
                    {this.state.newRequest.description !==
                    request.data.requestData.description
                      ? this.state.newRequest.description
                      : request.data.requestData.description}
                  </Text>
                  <Text>
                    Budget:{" "}
                    {this.state.newRequest.budget !==
                    request.data.requestData.budget
                      ? this.state.newRequest.budget
                      : request.data.requestData.budget}
                  </Text>
                  <Text>
                    Starting Date:{" "}
                    {this.state.newRequest.date !==
                    request.data.requestData.date
                      ? this.state.newRequest.date
                      : request.data.requestData.date}
                  </Text>
                </View>
              </Card>
              {request.data.editedImages.map((item, index) => {
                return (
                  <TouchableWithoutFeedback key={index}>
                    <Card>
                      {console.log("item.uri", item.uri)}
                      <Image
                        key={index}
                        style={{ width: 250, height: 250 }}
                        source={{ uri: item.uri }}
                      />
                    </Card>
                  </TouchableWithoutFeedback>
                );
              })}
            </ScrollView>
          </View>

          <View style={styles.buttons}>
            <TouchableOpacity
              style={styles.button}
              onPress={() => this.createNewReq()}
            >
              <MaterialIcons name="mode-edit" size={30} color="white" />
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.button}
              onPress={() => this.sendAsEmail()}
            >
              <MaterialIcons name="send" size={30} color="white" />
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.button}
              onPress={() => this.sendAsEmailToMany()}
            >
              <MaterialIcons name="share" size={30} color="white" />
            </TouchableOpacity>
          </View>
        </View>
      );
    } else {
      return (
        <View style={styles.container}>
          <Text> Waiting for data...</Text>
        </View>
      );
    }
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white"
  },
  paragraphText: {
    textAlign: "left",
    alignSelf: "flex-start",
    padding: 10
  },
  title: {
    fontSize: 24,
    color: "#0ec485"
  },
  tagline: {
    fontSize: 12
  },
  infos: {
    marginTop: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 }
  },
  buttons: {
    flexDirection: "row",
    alignSelf: "center",
    marginBottom: 60
  },
  button: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    borderWidth: 1,
    borderRadius: 50,
    margin: 10,
    width: 50,
    height: 50,
    backgroundColor: "#85c4ea",
    marginBottom: 10,
    borderColor: "#85c4ea"
  },
  request_card: {
    backgroundColor: "#fff",
    padding: 8,
    margin: 12,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: "#ddd",
    borderBottomWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2
  }
});
